_COLUMN_NAME_X_BJORKEN = "x_b"
_COLUMN_NAME_Q_SQUARED = "QQ"
_COLUMN_NAME_T_MOMENTUM_CHANGE = "t"
_COLUMN_NAME_AZIMUTHAL_PHI = "phi_"
_COLUMN_NAME_LEPTON_MOMENTUM = "k"

_COLUMN_NAME_CROSS_SECTION = "F"
_COLUMN_NAME_CROSS_SECTION_ERROR = "sigmaF"
